const MONTH_DURATION_DAYS = 30
const MONTH_DURATION_HOURS = MONTH_DURATION_DAYS * 24
const EXTRACT_NUMBER_RE = /.*?([0-9]+).*/
module.exports = {MONTH_DURATION_HOURS, MONTH_DURATION_DAYS, EXTRACT_NUMBER_RE}