const test = require('ava')

const tmp = {"mc_gross":9.99,"protection_eligibility":"Eligible","address_status":"unconfirmed","payer_id":"7ZJLV4V84GJMC","address_street":"Trubarjeva cesta 79","payment_date":"02:12:28 Jun 10, 2017 PDT","payment_status":"Completed","charset":"windows-1252","address_zip":"SI 1000","first_name":"Maksim","option_selection1":"003-sl_0006@003vendor.com","mc_fee":0.69,"address_country_code":"SI","address_name":"Maksim Rudolf","notify_version":3.8,"subscr_id":"I-94CP263S1UM8","payer_status":"verified","business":"birketrans@gmail.com","address_country":"Slovenia","address_city":"Ljubljana","verify_sign":"A21kmBLyRcQpDSjYvmswlm3ckjahAr6sOm3ZBvYJeKuVK4XURb7zBJna","payer_email":"maksim@maksimrudolf.com","option_name1":"GTT/Sesame email account","txn_id":"2B4788791Y9991157","payment_type":"instant","btn_id":135736277,"last_name":"Rudolf","address_state":"SI","receiver_email":"birketrans@gmail.com","payment_fee":null,"receiver_id":"ES39ZWNXE956L","txn_type":"subscr_payment","item_name":"Monthly subscription","mc_currency":"EUR","item_number":"subscribe_1_month","residence_country":"SI","transaction_subject":"Monthly subscription","payment_gross":null,"ipn_track_id":"e277610f02e2"}


const realPaymentObject = {
    '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@': '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@',
    'address_city': 'Bergen',
    'address_country': 'Norway',
    'address_country_code': 'NO',
    'address_name': 'Eirik Birkeland',
    'address_state': '',
    'address_status': 'unconfirmed',
    'address_street': 'Bj%F8rnsons+gate+22',
    'address_zip': '5059',
    'business': 'birketrans@gmail.com',
    'charset': 'windows-1252',
    'custom': '',
    'first_name': 'Eirik',
    'handling_amount': '0.00',
    'ipn_track_id': '3dac9a655f5bf',
    'item_name': 'Buy now - 3 months',
    'item_number': 'buynow_3_months',
    'last_name': 'Birkeland',
    'mc_currency': 'EUR',
    'mc_fee': '0.01',
    'mc_gross': '0.01',
    'notify_version': '3.8',
    'option_name1': 'GTT/Sesame email account',
    'option_selection1': '003-no_0024@003vendor.com',
    'payer_email': 'eirikbirkeland@gmail.com',
    'payer_id': 'ABAWF6CKLNM5G',
    'payer_status': 'unverified',
    'payment_date': '13:57:41 May 16, 2017 PDT',
    'payment_fee': '',
    'payment_gross': '',
    'payment_status': 'Completed',
    'payment_type': 'instant',
    'protection_eligibility': 'Ineligible',
    'quantity': '1',
    'receipt_id': '0436-9767-8425-4117',
    'receiver_email': 'birketrans@gmail.com',
    'receiver_id': 'ES39ZWNXE956L',
    'residence_country': 'NO',
    'shipping': '0.00',
    'tax': '0.00',
    'transaction_subject': '',
    'txn_id': '2DT82312JH028871G',
    'txn_type': 'web_accept',
    'verify_sign': 'A88bzkGGgvtCC.y2Ik0ws0aiHc-mAgD.ZNdp68Mu4hY62L2akRUkUatb',
}

const threeMonthsPayment = {
    '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@': '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@',
    'address_city': 'Bergen',
    'address_country': 'Norway',
    'address_country_code': 'NO',
    'address_name': 'test buyer',
    'address_state': 'Norge',
    'address_status': 'confirmed',
    'address_street': 'Bryggen 1',
    'address_zip': '5003',
    'business': 'birketrans-facilitator@gmail.com',
    'charset': 'windows-1252',
    'custom': '',
    'first_name': 'test',
    'ipn_track_id': '3f1807063a440',
    'item_name': 'Buy now - 3 months',
    'item_number': 'buynow_3_months',
    'last_name': 'buyer',
    'mc_currency': 'EUR',
    'mc_gross': '90.00',
    'notify_version': '3.8',
    'option_name1': 'GTT/Sesame email account',
    'option_selection1': 'birketrans@gmail.com',
    'payer_email': 'birketrans-buyer@gmail.com',
    'payer_id': '7QNBRXMHACYKE',
    'payer_status': 'verified',
    'payment_date': '12:49:46 Apr 08, 2017 PDT',
    'payment_gross': '',
    'payment_status': 'Pending',
    'payment_type': 'instant',
    'pending_reason': 'multi_currency',
    'protection_eligibility': 'Ineligible',
    'quantity': '1',
    'receiver_email': 'birketrans-facilitator@gmail.com',
    'receiver_id': 'ZUGRT9W5QNX2A',
    'residence_country': 'NO',
    'test_ipn': '1',
    'transaction_subject': '',
    'txn_id': '8W642954FE630740D',
    'txn_type': 'web_accept',
    'verify_sign': 'Axzuw7JO97QEsqqATqKWqCvWgYgbAAqqaF6O9tSdUgA3nJ75aisFT09L',
    _isADummyObject: 'true'
}


const subscriptionPayment = {
    '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@': '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@',
    'mc_gross': '28.00',
    'protection_eligibility': 'Ineligible',
    'address_status': 'unconfirmed',
    'payer_id': '7QNBRXMHACYKE',
    'address_street': 'Bryggen 1',
    'payment_date': '11:26:21 Apr 08, 2017 PDT',
    'payment_status': 'Completed',
    'charset': 'windows-1252',
    'address_zip': '5003',
    'first_name': 'test',
    'option_selection1': '003-no_0024@003vendor.com',
    'mc_fee': '1.25',
    'address_country_code': 'NO',
    'address_name': 'test buyer',
    'notify_version': '3.8',
    'subscr_id': 'I-3LGTHMSW1H4X',
    'payer_status': 'verified',
    'business': 'birketrans-facilitator@gmail.com',
    'address_country': 'Norway',
    'address_city': 'Bergen',
    'verify_sign': 'AiPC9BjkCyDFQXbSkoZcgqH3hpacAH9ca9RTluH1OEfFJuydEvanV6-m',
    'payer_email': 'birketrans-buyer@gmail.com',
    'option_name1': 'Your GTT email account:',
    'txn_id': '2GT82980FT264610W',
    'payment_type': 'instant',
    'btn_id': '3530446',
    'last_name': 'buyer',
    'address_state': 'Norge',
    'receiver_email': 'birketrans-facilitator@gmail.com',
    'payment_fee': '1.25',
    'receiver_id': 'ZUGRT9W5QNX2A',
    'txn_type': 'subscr_payment',
    'item_name': 'Monthly subscription',
    'mc_currency': 'EUR',
    'item_number': 'subscribe_1_month',
    'residence_country': 'NO',
    'test_ipn': '1',
    'transaction_subject': 'Monthly subscription',
    'payment_gross': '28.00',
    'ipn_track_id': 'f95d165543801',
    _isADummyObject: 'true'
}

const subscriptionPaymentMeta = {
    '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@': '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@',
    'address_city': 'Bergen',
    'address_country': 'Norway',
    'address_country_code': 'NO',
    'address_name': 'test buyer',
    'address_state': 'Norge',
    'address_status': 'unconfirmed',
    'address_street': 'Bryggen 1',
    'address_zip': '5003',
    'amount3': '28.00',
    'btn_id': '3530446',
    'business': 'birketrans-facilitator@gmail.com',
    'charset': 'windows-1252',
    'first_name': 'test',
    'ipn_track_id': 'f95d165543801',
    'item_name': 'Monthly subscription',
    'item_number': 'subscribe_1_month',
    'last_name': 'buyer',
    'mc_amount3': '28.00',
    'mc_currency': 'EUR',
    'notify_version': '3.8',
    'option_name1': 'Your GTT email account:',
    'option_selection1': '003-no_0024@003vendor.com',
    'payer_email': 'birketrans-buyer@gmail.com',
    'payer_id': '7QNBRXMHACYKE',
    'payer_status': 'verified',
    'period3': '1 M',
    'reattempt': '1',
    'receiver_email': 'birketrans-facilitator@gmail.com',
    'recurring': '1',
    'residence_country': 'NO',
    'subscr_date': '11:26:17 Apr 08, 2017 PDT',
    'subscr_id': 'I-3LGTHMSW1H4X',
    'test_ipn': '1',
    'txn_type': 'subscr_signup',
    'verify_sign': 'AQU0e5vuZCvSg-XJploSa.sGUDlpAclMzAkLPMiMw9-ktNy5GYpWdKWX',
    _isADummyObject: 'true'
}

const unofficialPayment = {
    '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@': '@@@@@@@@@THIS-IS-A-UNIT-TEST@@@@@@@@@',
    transaction_subject: '',
    txn_type: 'send_money',
    payment_date: '16:2:47 May 3, 217 PDT',
    last_name: 'buyer',
    residence_country: 'NO',
    payment_gross: '',
    mc_currency: 'NOK',
    business: 'birketrans-facilitator@gmail.com',
    payment_type: 'instant',
    protection_eligibility: 'Eligible',
    verify_sign: 'AqoHtf-9ou72KnSG8v3.87oYuH7IASet34Q7jmS2A7Z6JlUTfNhM.SQ2',
    payer_status: 'verified',
    test_ipn: '1',
    payer_email: 'birketrans-buyer-1@gmail.com',
    txn_id: '91U522781W211933',
    receiver_email: 'birketrans-facilitator@gmail.com',
    first_name: 'test',
    payer_id: 'C7P6XRQJG9DC2',
    receiver_id: 'ZUGRT9W5QNX2A',
    payer_business_name: 'bedrift1',
    payment_status: 'Completed',
    mc_gross: '100000.00',
    charset: 'windows-1252',
    notify_version: '3.8',
    ipn_track_id: '5272cccccaeae',
    _isADummyObject: 'true'
}

module.exports = {
    realPaymentObject,
    threeMonthsPayment,
    subscriptionPayment,
    subscriptionPaymentMeta,
    unofficialPayment,
    tmp
}
